POST http://localhost:8080/api/auth/local/register
Content-Type: application/json

{
    "username": "sittipong111",
    "email": "s6602041520ssss268@email.kmutnb.ac.t12h",
    "password": "0883450013ket1"

}